routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ClintController as UnClientControler;
use App\Http\Livewire\ClientController;
use App\Http\Livewire\PostController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('webSite.home');
});

Route::view('/home', 'webSite.home')->name('home');

Route::get('servicio/{slug}',       [ServiceController::class, 'index'])->name('service.home');
Route::post('contact/save',         [ServiceController::class, 'save'])->name('service.contact');
Route::get('blog/{slug?}',          [BlogController::class, 'index'])->name('webSite.blog');
Route::post('blog/comment/{id}',    [BlogController::class, 'saveComment'])->name('blog.saveComment');
Route::post('landing/save',         [LandingPageController::class, 'save'])->name('landing.save');
Route::get('/darse-de-baja',        [UnClientControler::class, 'index'])->name('webSite.unsubscription');
Route::delete('/darse-de-baja',     [UnClientControler::class, 'handleDelete'])->name('webSite.unsubscription');




Route::view('/contacto', 'webSite.contact')->name('webSite.contact');

Route::view('/formacion', 'webSite.service.study')->name('webSite.service.study');

Route::view('/sobre-nosotros', 'webSite.about')->name('webSite.about');

Route::view('/formación', 'webSite.landing')->name('webSite.landing');

Route::view('/usurio-no-registrado', 'webSite.nofaind')->name('webSite.nofaind');

Route::view('/delete_user', 'webSite.deleteUser')->name('webSite.deleteUser');





Auth::routes();


//protección de las rutas para que solo los usuarios autenticados tengan acceso

Route::middleware(['auth','role'])->group( function() {
	Route::view('dashboard',        'layouts.dashboard');
	Route::view('user',             'user')->name('user');
	Route::view('servicios',        'service')->name('service');
	Route::view('job/team',         'jobTeam')->name('jobTeam');
	Route::view('service/client',   'ServiceHasClient')->name('ServiceHasClient');
	
    Route::get('client',       ClientController::class)->name('client');
		
});


Route::middleware(['auth'])->group( function() {
    Route::get('post',         PostController::class)->name('post');
});

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'posts';

    protected $fillable = [
        'name',
        'description',
        'user_id',
        'slug',
        'image',
        'status'
    ];

    const ACTIVE = 'ACTIVO';

    const NAME = [
        'Post-prueba',  
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    // scope
    public function scopeActive($query)
    {
        return $query->where('status', Post::ACTIVE);
    }

    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', $slug);
    }

    public function scopeHandlerNotPost($query, array $array)
    {
        return $query->whereNotIn('id', $array);
    }

    // Accessor

    public function getFullCreatedAtAttribute() {
        return Carbon::parse($this->created_at)->toFormattedDateString().' - '.Carbon::parse($this->created_at)->format('h:i A');
    }

    public function getFullUpdatedAtAttribute() {
        return Carbon::parse($this->updated_at)->toFormattedDateString().' - '.Carbon::parse($this->updated_at)->format('h:i A');
    }

    public function getDescriptionShortAttribute(){
        
        return substr($this->description,0,100);
        
    }
}

app/Http/Livewire/ClientController.php
<?php

namespace App\Http\Livewire;

use App\Models\Client;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use Illuminate\Support\Facades\Route;

class ClientController extends Component
{
    use WithPagination, WithFileUploads;

    protected $paginationTheme = 'bootstrap';//poder utilizar la paginación en laravel 8

    public $pagination = 10, $search, $action = 1, $edit = 1, $component = 'clientes';
    public $selected_id, $client;

    public function mount(){
        $this->url = Route::current()->getName();
    }

    public function render()
    {

        try {
            if ($this->search) {
                $clients = Client::Search($this->search);
            }else{
                $clients = Client::orderBy('id','desc');
            }
            return view('livewire.Client.component',[
                'clients'  => $clients->paginate($this->pagination),
            ])->extends('layouts.dashboard')->section('content');
        } catch (\Exception $e) {
           return $e;
        }
    }

    //permite la búsqueda cuando se navega entre el paginado
    public function updatingSearch(){
        $this->gotoPage(1);
    }

    public function handleAction($action)
    {
        $this->action = $action;
    }

    public function edit(Client $client)
    {
        $this->edit             = 2;
    	$this->client           = $client;
    	$this->selected_id      = $client->id;
    }

    protected $listeners = ['handleDelete'];

    public function handleDelete(Client $client, $action ){
        $client->delete();
        $client->comments()->delete();
        $client->servicesHasclients()->delete();
        $this->emit('msgok','El cliente '.$client->name.', ha sido eliminado');
        $this->handleAction($action);
    }

}

app/Http/Livewire/JobTeamController.php
<?php

namespace App\Http\Livewire;

use App\Models\JobTeam;
use Livewire\Component;
use App\Models\User;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use Carbon\Carbon;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Route;

class JobTeamController extends Component
{
    use WithPagination, WithFileUploads;

    protected $paginationTheme = 'bootstrap';//poder utilizar la paginación en laravel 8

    public $pagination = 10, $search, $action = 1, $edit = 1, $component = 'Colaboradores';
    public $roles;
    public $name, $user, $position, $profile, $phone, $image, $status = 'Elegir', $selected_id;


    public function mount(){
        $this->url   = Route::current()->getName();

    }

    public function render()
    {
        try {
            if ($this->search) {
                $jobTeams = JobTeam::Search($this->search);
            }else{
                $jobTeams = JobTeam::orderBy('id','desc');
            }
            return view('livewire.jobTeam.component',[
                'jobTeams'  => $jobTeams->paginate($this->pagination),
            ]);
        } catch (\Exception $e) {
           $this->emit('msg-error', $e->getMessage());
        }
    }

    //permite la búsqueda cuando se navega entre el paginado
    public function updatingSearch(){
        $this->gotoPage(1);
    }

    public function handleAction($action)
    {
        $this->handleReset($action);
    }

    // limpiar
    public function handleReset($action)
    {
        $this->name             = '';
        $this->user             = '';
        $this->position         = '';
        $this->profile          = '';
        $this->phone            = '';
        $this->count            = 1;
        $this->action           = $action;
        $this->edit             = 1;
        $this->image            = null;
        $this->selected_id      = null;
        $this->status           = 'Elegir';
    }

    public function StoreOrUpdate($action)
    {
        $this->validate([               
                'name'                => 'bail|required|string|min:3|max:255',
                'phone'               => 'bail|required|numeric|digits_between:5,10|unique:job_teams,phone,'.$this->selected_id,
                'position'            => 'bail|required|string|min:3|max:255',
                'profile'             => 'bail|required|string|min:3|max:255',
                'image'               => 'bail|nullable|image|max:4112',
                'status'              => 'bail|required|string|min:3|max:255',
            ],
            [
                'phone.unique'          => 'El telefono ya se encuentra registrado',
            ]
        );
        try {


            $find = [
                'id'  => $this->selected_id,
            ];
            $data = [
                'name'              => $this->name,
                'position'          => $this->position,
                'profile'           => $this->profile,
                'phone'             => $this->phone,
                'status'            => $this->status,
            ];

            if ($this->selected_id) {
                $updateOrCreate = 'actualizado';
            }else{
                $updateOrCreate = 'creado';
            }

            $jobTeam = JobTeam::updateOrCreate($find, $data);

            if ($this->image) {
                $image      = $this->image;
                $fileName   = time() . '.' . $image->getClientOriginalExtension();
                $moved      = \Image::make($image)->save('image/jobTeams/'.$fileName);
                if ($moved) {
                    $jobTeam->image = $fileName;
                    $jobTeam->save();
                }
            }

            $this->emit('msgok','El usuario '.$jobTeam->name.', ha sido '.$updateOrCreate);
            $this->emit('modalsClosed', $this->component.'-component');

        } catch (\Exception $e) {
            $this->emit('msg-error', $e->getMessage());
        }

        $this->handleReset($action);
    }

    public function edit(JobTeam $user)
    {
    	$this->user             = $user;
    	$this->selected_id      = $user->id;
    	$this->name             = $user->name;
    	$this->position         = $user->position;
    	$this->profile          = $user->profile;
    	$this->phone            = $user->phone;
    	$this->status           = $user->status;
    	$this->edit             = 2;
    }

    protected $listeners = ['handleDelete'];


    public function handleDelete(JobTeam $user, $action ){
        $user->delete();
        $this->emit('msgok','Usuario '.$user->name.', ha sido eliminado');
        $this->handleReset($action);
    }
}

app/Http/Livewire/PostController.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\CommentResponse;
use App\Models\Post;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Livewire\Component;
use Livewire\WithFileUploads;
use Livewire\WithPagination;
use Illuminate\Support\Facades\Route;


class PostController extends Component
{
    use WithPagination, WithFileUploads;

    protected $paginationTheme = 'bootstrap';//poder utilizar la paginación en laravel 8

    public $pagination = 10, $search, $action = 1, $edit = 1, $component = 'post';
    public $name, $post, $description, $image, $user_id = 'Elegir', $users, $status = 'Elegir', $selected_id;
    public $comment;

    public function mount(){
        $this->url      = Route::current()->getName();
        $this->users    = User::admin()->active()->orderBy('name')->get();
    }

    public function render()
    {
        try {
            if ($this->search) {
                $posts = Post::Search($this->search);
            }else{
                $posts = Post::orderBy('id','desc');
            }
            return view('livewire.post.component',[
                'posts'  => $posts->paginate($this->pagination),
            ])->extends('layouts.dashboard')->section('content');
        } catch (\Exception $e) {
           return $e;
        }
    }

    //permite la búsqueda cuando se navega entre el paginado
    public function updatingSearch(){
        $this->gotoPage(1);
    }

    public function handleAction($action)
    {
        $this->handleReset($action);
    
    }

    public function handleReset($action)
    {
        $this->name             = '';
        $this->post             = null;
        $this->comment          = null;
        $this->description      = '';
        $this->user_id          = 'Elegir';
        $this->count            = 1;
        $this->action           = $action;
        $this->edit             = 1;
        $this->selected_id      = null;
        $this->image            = null;
        $this->status           = 'Elegir';
        $this->emit('clearCkEditor');
        $this->emit('initializeCkEditor');
    }

    public function StoreOrUpdate($action)
    {
        try {
            $this->validate([
                    'description'           => 'bail|required|min:3|max:10000|string',
                    'name'                  => 'bail|required|string|min:3|max:255|unique:posts,name,'.$this->selected_id,
                    'image'                 => 'bail|nullable|image|max:4112',
                    'user_id'               => 'bail|required|not_in:Elegir',
                    'status'                => 'bail|required|not_in:Elegir',
                ],
                [
                    'name.unique'           => 'El nombre ya se encuentra registrado',
                ]
            );

            $find = [
                'id'  => $this->selected_id,
            ];     
            $data = [
                'name'              => $this->name,
                'description'       => $this->description,
                'slug'              => strtr($this->name, " ", "-"),
                'user_id'           => $this->user_id,
                'status'            => $this->status,
            ];
            
            //  dd($data);
            
            if ($this->selected_id) {
                $updateOrCreate = 'actualizado';
            }else{
                $updateOrCreate = 'creado';
            }

            $post = Post::updateOrCreate($find, $data);

            if ($this->image) {
                $image      = $this->image;
                $fileName   = time() . '.' . $image->getClientOriginalExtension();
                $moved      = \Image::make($image)->save('image/post/'.$fileName);
                if ($moved) {
                    $post->image = $fileName;
                    $post->save();
                }
            }

            $this->emit('msgok','El post '.$post->name.', ha sido '.$updateOrCreate);
            $this->emit('modalsClosed', $this->component.'-component');
            
        } catch (\Exception $e) {
            $this->emit('msg-error', $e->getMessage());
        }

        $this->handleReset($action);

        
    }

    public function edit(Post $post, $action, $edit = 2)
    {

    	$this->post             = $post;
    	$this->selected_id      = $post->id;
    	$this->name             = $post->name;
    	$this->description      = $post->description;
    	$this->status           = $post->status;
    	$this->user_id          = $post->user_id;
    	$this->edit             = $edit;
    	$this->action           = $action;
        $this->image            = null;
        $this->emit('clearCkEditor', $this->description);
        $this->emit('initializeCkEditor');

        // $this->emit('clearCkEditor');
    }

    public function editCommentResponse(Comment $comment, Post $post, $action)
    {
        $this->edit($post, $action, 3);
    	$this->comment = $comment;
    }

    protected $listeners = [
        'handleDelete',
        'handleDeleteComment',
        'handlerStatusComment',
        'handleDeleteCommentResponse',
        'addCommentResponse'
    ];

    public function handleDelete(Post $post, $action ){
        $post->delete();
        $post->comments()->delete();
        $this->emit('msgok','Post '.$post->name.', ha sido eliminado');
        $this->handleReset($action);
    }

    public function handleDeleteComment(Comment $comment, Post $post, $action){
        $comment->delete();
        $comment->commentResponses()->delete();
        $this->emit('msgok','El comentario ha sido eliminado');
        $this->edit($post, $action, 2);
    }

    public function handleDeleteCommentResponse(CommentResponse $comment, Post $post, $action){
        $comment->delete();
        $this->emit('msgok','El comentario ha sido eliminado');
        $this->edit($post, $action, 2);
    }

    public function handlerStatusComment(Comment $comment, Post $post, $action){
        $comment->update([
            'status' => $comment->status == 'ACTIVO' ? 'DESACTIVADO':'ACTIVO'
        ]);
        $this->emit('msgok','El comentario ha sido actualizado');
        $this->edit($post, $action, 2);
    }

    public function addCommentResponse($comment_id, $description, Post $post, $action){
        CommentResponse::create([
            'comment_id'    => $comment_id,
            'user_id'       => Auth::user()->id,
            'description'   => $description,
        ]);
        $this->emit('msgok','Se ha agregado una respuesta a un comentario');
        $this->edit($post, $action, 2);
    }

   

    
}

resources/views/livewire/post/modals.blade.php
 <!-- Modal create servicio -->
 <div wire:ignore.self class="modal fade" id="{{$component}}-component" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content ">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">{{ $edit == 1 ? 'Crear':'Editar'}}  post</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form class="modal-body" wire:submit.prevent="store(document.querySelector('#yourTextAreaId').value)" >
            <div class="form-group  col-sm-12">
                <label>Titulo</label>
                <input wire:model.lazy="name" type="text" class="form-control"  placeholder="Nombre">
            </div>
            <div class="form-group  col-sm-12" id="textarea"  wire:ignore>
                <label>Descripción</label> 
                <textarea  id="ckeditor" wire:model.lazy="description" type="text"  class="form-control" cols="10" rows="4" name="description"> </textarea>               
            </div>
            <div class="form-group  col-sm-12">
                <label>{{$edit == 1 || !$post->image ? 'Cargar':'Editar'}} imagen</label>
                @if ($edit == 2)
                    <div class="mb-2 text-center">
                        @if ($post->image)
                            <img class="rounded-circle" width="200px" height="200px" src="{{ asset('image/post/'.$post->image) }}">
                        @endif
                    </div>
                @endif
                <input type="file" class="form-control text-center" id="image"
                    wire:model="image" accept="image/x-png, image/gif, image/jpeg"
                >
            </div>
            <div class="form-group  col-sm-12">
                <label >Publicado por</label>
                <select wire:model="user_id" class="form-control">
                    <option selected value="Elegir" disabled="true">Elegir</option>
                    @foreach ($users as $user)
                        <option value="{{$user->id}}">{{$user->name}}</option>
                    @endforeach
                </select>
            </div>
            <div class="form-group  col-sm-12">
                <label >Estado*</label>
                <select wire:model="status" class="form-control">
                    <option selected value="Elegir" disabled="true">Elegir</option>
                    <option value="ACTIVO">ACTIVO</option>
                    <option value="DESACTIVADO">DESACTIVADO</option>
                </select>
            </div>
        </form>
        <div class="mt-2">
            @include('common.messages')
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-dark" data-dismiss="modal">Cerrar</button>
          <button type="button" wire:click="StoreOrUpdate(1)" class="btn btn-primary" >Guardar</button>
        </div>
    </div>

    </div>
</div>


<!-- Modal respuesta de comentario -->
<div wire:ignore.self class="modal fade" id="response-comment" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Respuesta de comentario</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        @if ($edit == 3)

        <div class="modal-body">
            <div class="widget-one">
                @if($comment->commentResponses->count())
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-bordered" id="dataTablecommentResponses" width="100%" cellspacing="0">
                                <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Respuesta</th>
                                    <th>Fecha</th>
                                    <th style="text-align: center;">Acciones</th>
                                </tr>
                                </thead>
                                <tbody>
                                    @foreach ($comment->commentResponses as $commentResponse)
                                        <tr>
                                            <td>{{$commentResponse->user->name}}</td>
                                            <td>{{$commentResponse->description}}</td>
                                            <td>{{$commentResponse->full_created_at}}</td>
                                            <td style="text-align: center;">
                                                <ul class="table-controls row d-flex justify-content-between mb-1 mt-1 gap-2" style="list-style-type: none;">
                                                    <li>
                                                        <a class="btn button--md btn-danger btn-icon-split text-decoration-none c-pointer" onclick="deleteComment({{$commentResponse->id}}, {{$comment->post_id}}, 2,'handleDeleteCommentResponse')">
                                                            <span class=" text-white-50 icon padding-0-6 padding-l-1-2">
                                                                <i class="fas fa-trash "></i>
                                                            </span>
                                                        </a>
                                                    </li>
                                                </ul>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                @else
                    <h2>Sin respuestas...</h2>
                @endif
            </div>
        <div class="modal-footer">
            <a class="btn btn-info btn-icon-split" onclick="addCommentResponse({{$comment->id}}, {{$comment->post_id}}, 2)">
                <span class="icon text-white-50">
                <i class="fas fa-edit"></i>
                </span>
                <span class="text">Agregar respuesta</span>
            </a>
          <button type="button" class="btn btn-dark" data-dismiss="modal">Cerrar</button>
        </div>
    </div>
    @endif


    </div>
</div>

resources/views/livewire/post/show.blade.php
<div class="widget-content-area card-body ">
    <div class="widget-header">
        <div class="row">
            <div class="col-xl-12 text-center">
                <h5><b>Información del la prublicación</b></h5>
                <hr>
            </div>
        </div>
    </div>
    <div class="widget-one">
        <div class="row">
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Titulo</label>
                <h6 class=""><b>{{$post->name}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Descripción</label>
                <div  style="  display: -webkit-box;
                overflow: hidden;
                -webkit-box-orient: vertical;
                -webkit-line-clamp: 2"><p>{!! $post->description !!}</p></div>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Publicado por</label>
                <h6 class=""><b>{{$post->user->name}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Imagen</label>
                @if ($post->image)
                    <img width="200px" height="200px" src="{{ asset('image/post/'.$post->image) }}">
                @else
                    <h6 class=""><b>No tiene imagen...</b></h6>
                @endif
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Fecha de publiación</label>
                <h6 class=""><b>{{$post->full_created_at}}</b></h6>
            </div>
            <div class="form-group col-lg-4 col-md-4 col-sm-12">
                <label >Última modificación</label>
                <h6 class=""><b>{{$post->full_updated_at}}</b></h6>
            </div>
        </div>
    </div>
    <br>
    <div class="widget-content-area">
        <div class="widget-header">
            <div class="row">
                <div class="col-xl-12 text-center">
                    <h5><b>Comentarios</b></h5>
                    <hr>
                </div>
            </div>
        </div>
        <div class="widget-one">
            @if($post->comments->count())
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                            <thead>
                            <tr>
                                <th>Cliente</th>
                                <th>Comentario</th>
                                <th>Estado</th>
                                <th style="text-align: center;">Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                                @foreach ($post->comments as $comment)
                                    <tr>
                                        <td>{{$comment->client->name}}</td>
                                        <td>{{$comment->description}}</td>
                                        <td>{{$comment->status}}</td>
                                        <td style="text-align: center;">
                                            <ul class="table-controls row d-flex justify-content-between mb-1 mt-1 gap-2" style="list-style-type: none;">
                                                <li>
                                                    <a class="btn button--md btn-info btn-icon-split text-decoration-none c-pointer text-light" onclick="handlerStatusComment({{$comment->id}}, {{$comment->post_id}}, 2, '{{$comment->status}}')">
                                                        <span class="text-white-50 icon  ">
                                                            <i class="fas fa-edit padding-0-6"></i>
                                                        </span>
                                                        <span class="text ">{{$comment->status == 'ACTIVO' ? 'Deshabilitar':'Habilitar'}} </span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a wire:click="editCommentResponse({{$comment->id}}, {{$comment->post_id}}, 2)" class="btn button--md btn-success btn-icon-split text-decoration-none c-pointer"  data-toggle="modal" data-target="#response-comment">
                                                        <span class="text-white-50 icon padding-0-6 padding-l-1-2">
                                                            <i class="fas fa-audio-description"></i>
                                                        </span>
                                                        <span class="text">Respuesta</span>
                                                    </a>
                                                </li>
                                                <li>
                                                    <a class="btn button--md btn-danger btn-icon-split text-decoration-none c-pointer" onclick="deleteComment({{$comment->id}}, {{$comment->post_id}}, 2, 'handleDeleteComment')">
                                                        <span class=" text-white-50 icon padding-0-6 padding-l-1-2">
                                                            <i class="fas fa-trash "></i>
                                                        </span>
                                                        <span class="text ">Delete </span>
                                                    </a>
                                                </li>
                                            </ul>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            @else
                <h2>Sin comentarios...</h2>
            @endif
        </div>
    </div>
    <div class="row ">
        <div class="col-lg-5 mt-2  text-left">
            <button type="button" wire:click="handleAction(1)" class="btn btn-dark mr-1">
                <i class="mbri-left"></i> Regresar
            </button>
        </div>
    </div>
</div>