routes/web.php
<?php

use App\Http\Controllers\BlogController;
use App\Http\Controllers\LandingPageController;
use App\Http\Controllers\ServiceController;
use App\Http\Controllers\ClintController as UnClientControler;
use App\Http\Livewire\ClientController;
use App\Http\Livewire\PostController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('webSite.home');
});

Route::view('/home', 'webSite.home')->name('home');

Route::get('servicio/{slug}',       [ServiceController::class, 'index'])->name('service.home');
Route::post('contact/save',         [ServiceController::class, 'save'])->name('service.contact');
Route::get('blog/{slug?}',          [BlogController::class, 'index'])->name('webSite.blog');
Route::post('blog/comment/{id}',    [BlogController::class, 'saveComment'])->name('blog.saveComment');
Route::post('landing/save',         [LandingPageController::class, 'save'])->name('landing.save');
Route::get('/darse-de-baja',        [UnClientControler::class, 'index'])->name('webSite.unsubscription');
Route::delete('/darse-de-baja',     [UnClientControler::class, 'handleDelete'])->name('webSite.unsubscription');




Route::view('/contacto', 'webSite.contact')->name('webSite.contact');

Route::view('/formacion', 'webSite.service.study')->name('webSite.service.study');

Route::view('/sobre-nosotros', 'webSite.about')->name('webSite.about');

Route::view('/formación', 'webSite.landing')->name('webSite.landing');

Route::view('/usurio-no-registrado', 'webSite.nofaind')->name('webSite.nofaind');

Route::view('/delete_user', 'webSite.deleteUser')->name('webSite.deleteUser');





Auth::routes();


//protección de las rutas para que solo los usuarios autenticados tengan acceso

Route::middleware(['auth','role'])->group( function() {
	Route::view('dashboard',        'layouts.dashboard');
	Route::view('user',             'user')->name('user');
	Route::view('servicios',        'service')->name('service');
	Route::view('job/team',         'jobTeam')->name('jobTeam');
	Route::view('service/client',   'ServiceHasClient')->name('ServiceHasClient');
	
    Route::get('client',       ClientController::class)->name('client');
		
});


Route::middleware(['auth'])->group( function() {
    Route::get('post',         PostController::class)->name('post');
});

app/Models/Post.php
<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Post extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'posts';

    protected $fillable = [
        'name',
        'description',
        'user_id',
        'slug',
        'image',
        'status'
    ];

    const ACTIVE = 'ACTIVO';

    const NAME = [
        'Post-prueba',  
    ];

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function comments() {
        return $this->hasMany(Comment::class);
    }

    // scope
    public function scopeActive($query)
    {
        return $query->where('status', Post::ACTIVE);
    }

    public function scopeSlug($query, $slug)
    {
        return $query->where('slug', $slug);
    }

    public function scopeHandlerNotPost($query, array $array)
    {
        return $query->whereNotIn('id', $array);
    }

    // Accessor

    public function getFullCreatedAtAttribute() {
        return Carbon::parse($this->created_at)->toFormattedDateString().' - '.Carbon::parse($this->created_at)->format('h:i A');
    }

    public function getFullUpdatedAtAttribute() {
        return Carbon::parse($this->updated_at)->toFormattedDateString().' - '.Carbon::parse($this->updated_at)->format('h:i A');
    }

    public function getDescriptionShortAttribute(){
        
        return substr($this->description,0,100);
        
    }
}

resources/views/webSite/about.blade.php
@extends('layouts.app')

@section('content')

<div class="main-container padding-b-2">

    <section class="hero margin-b-0 d-md-flex flex-column justify-content-sm-center position-relative">
        <div class="hero__layer"></div>
        <div class="hero__section text-light d-none  d-md-flex align-items-center gap-2 position-absolute"><i class="icon-home fs-4"></i><i class="icon-circle font-s-0-2"></i> <h1 class="font-w-7 l-spacing-5 fs-3">Sobre Nosotros</h1></div>

        <picture >
            <source srcset="../../assets/img/consultancy_d.webp" media="(min-width:768px)">
             <img class="hero_home-image w-100" src="../../assets/img/consultancy_m.webp" alt="Sobre Cv Auditores de Colombia SAS">
          </picture>
    </section>


    <section class="padding-x-2 padding-3-md">

        <div class="">
            <div class="mt-5 mb-4">
                <h2 class="fw-bold">Valores Corporativos</h2>
            </div>

            <div class="">
                <ul class="list-style-none px-0 container-card-value gap-5">
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Sentido de Pertenencia</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Trabajo en Equipo</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Motivación al Logro</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Compromiso con su Gente</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Excelencia</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Respeto</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Veracidad</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Responsabilidad Social</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                    <li class="p-4 width-100  back-white my-4"> <a class="text-primary text-decoration-none fs-1" href="">Honestidad</a> <p class="mt-3">Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam</p> </li>
                  
                </ul>
            </div>
        </div>


    </section>

    <section class="d-flex flex-column flex-md-row">
        <article class="bg-primary text-light p-4 h-20 h-28-lg w-100 d-flex justify-content-center align-items-center">
            <div class="card--corpo">
                <h2>Visión</h2>

                <p class="text-a-j mt-4">Ser la organización líder en Revisoría Fiscal, Auditoría y Consultoría especializada a nivel nacional, utilizando estándares internacionales y nuestro servicio personalizado de alta calidad y ética profesioanl. </p>
            </div>
        </article>
        <article class=" back-white p-4 h-20 h-28-lg w-100 d-flex justify-content-center align-items-center">
            <div class="card--corpo">
                <h2>Misión</h2>

                <p class="text-a-j mt-4">Asegurar un excelente servicio a nuestros clientes, en la búsqueda de soluciones eficaces para sus negocios dentro del marco administrativo y legal con el propósiton de coadyudar eficientemente al logro de sus objetivos.</p>
            </div>
        </article>
    </section>



    <section class="mt-4 px-3 ">

            <article class="container-card-teem">
                @foreach ($jobTeamsGlobal as $jobTeam)
                <div class="border back-white d-flex flex-md-column w-15-lg card-teem">
                    <div class="card-teem__picture">
                        @if ($jobTeam->image)
                            <img class="" width="140px" height="200px" src="{{ asset('image/jobTeams/'.$jobTeam->image) }}" alt="{{$jobTeam->name}}">
                        @else
                        
                        <picture >
                                <img class="" src="../../assets/img/teem/avatar_teem.png" alt="{{$jobTeam->name}}">
                        </picture>
                           
                        @endif
                    </div>
                    <div class="card-teem__text">
                        <div class="mt-3"><span class="text-uppercase color-gray5">{{$jobTeam->position}}</span></div>
                        <div class="text-primary font-s-lg-1-5"><span>{{$jobTeam->name}}</span></div>
                        <div class="font-s-0-6 font-s-lg-1 my-2" ><span  >{{$jobTeam->profile}}</span></div>
                        <div class="font-s-0-8 "><i class="icon-phone color-gray5 "></i><span class="color-gray5">{{$jobTeam->phone}}</span></div>
                    </div>
                </div>
            @endforeach
            </article>


    </section>


</div>

@endsection

resources/views/webSite/blog.blade.php
@extends('layouts.app')

@section('content')

<div class="main-container">

    <section class="hero d-md-flex flex-column justify-content-sm-center position-relative">
        <div class="hero__layer d-flex justify-content-center align-items-center">
            <div class="text-light text-center">
                <h1 class="font-w-7 l-spacing-5 font-calc-1"> REVISORÍA FISCAL Y ACTUALIZACIÓN EN AUDITORÍA</h1>
                <span class="fs-6 d-none d-md-block">Encuentra las últimas actualizaciones en Revisoría Fiscal y temas relacionados para tu empresa </span>
            </div>
        </div>
        <picture >
            <source srcset="../../assets/img/revision_d.webp" media="(min-width:768px)">
             <img class="hero_home-image w-100" src="../../assets/img/revision_m.webp" alt="Blog ACTUALIZACIÓN EN AUDITORÍA Y REVISORÍA FISCAL ">
          </picture>
    </section>

    <section class="padding-x-1 padding-x-2-md">

        <article class="d-flex flex-column flex-md-row gap-2 max-widt-32 max-widt-45-md max-widt-60-lg mx-auto mb-5">
            @foreach ($posts as $key => $item)
                @if ($key < 2)
                    <div class="d-flex border border-1 bg-light w-50vw-md ">
                        <div class="p-4">
                            <div><h2 class="card-blog__name fw-bold compr-text" >{{$item->name}}</h2></div>
                            <div class="card-blog__date">{{$item->full_created_at}}</div>
                            <div class="">
                            <p id="" class="card-blog__decription ">Para conocer más detalles sobre este interesante post, has click para <a href="{{route('webSite.blog', $item->slug)}}">continuar leyendo</a> </p>
                            {{-- <p id="" class="card-blog__decription">{!!$item->description_short!!}...</p> --}}
                           </div>
                            {{-- <a href="{{route('webSite.blog', $item->slug)}}">Continuar leyendo</a> --}}
                        </div>
                        <div class="d-none d-lg-block">
                            @if ($item->image)

                            <img class="h-100" src="{{ asset('image/post/'.$item->image) }}" alt="{{$item->name}}" title="{{$item->name}}"> 
                                
                            @else

                            <img class="h-100" src="../../assets/img/logo_blog_card.png" alt="{{$item->name}}" title="{{$item->name}}">
                                
                            @endif
                        </div>
                    </div>
                @endif
            @endforeach
        </article>
      
        <article class="d-flex flex-column flex-md-row max-widt-32 max-widt-45-md max-widt-60-lg mx-auto gap-4">

            <article class="w-50vw-md">
                <div class="">
                    <br>
                    <h2>{{$post->name}}</h2>
                    <span> <strong> {{$post->full_created_at}} por  {{$post->user->name}} </strong></span>
                </div>
                <hr>
                <div class="mb-5 " >
                    <p>{!! $post->description !!}</p>
                </div>

                <hr>
                <div>
                    <form method="POST" action="{{route('blog.saveComment', $post->id)}}">

                        @csrf
                        <h3>Dejanos conocer tus comentarios</h3>

                            <textarea class="form-coment form-coment__text resize-none" name="description" cols="" rows="10" required></textarea>
                            <div class="d-flex flex-column flex-md-row gap-3">
                                <input class="form-coment  form-content_input" type="text" name="name" placeholder="Nombre" required>
                                <input class="form-coment  form-content_input" type="email" name="email" placeholder="Correo Eléctronico" required>
                            </div>
                            <div class="my-3">
                                <button class="btn btn-danger" type="submit">Enviar</button>

                            </div>

                    </form>
                </div>

                <div class="">
                    <h3>Comentarios</h3>
                    @if ($post->comments()->active()->count() > 0)
                        @foreach ($post->comments as $item)
                            @if ($item->status == 'ACTIVO')
                                <div class="d-flex flex-column border border-1 back-white my-3">
                                    <div class="p-3">
                                        <div class="card-response__name fw-bold">{{$item->client->name}}</div>
                                        <div class="card-response__date">{{$item->full_created_at}}</div>
                                        <div class="mt-4 text-justify"><p>{{$item->description}} </p></div>
                                    </div>
                                </div>
                                @if ($item->commentResponses->count() > 0)
                                    <div class="margin-l-2 "><i class="icon-reply"></i>Respuesta a:<span class="fst-italic ms-1">{{$item->client->name}}</span></div>
                                    @foreach ($item->commentResponses as $response)
                                        <div class="margin-l-2 d-flex flex-column border border-1 back-white mb-5">
                                            <div class="p-3">
                                                <div class="card-response__name fw-bold">{{$response->user->name}}</div>
                                                <div class="card-response__date">{{$response->full_created_at}}</div>
                                                <div class="mt-4 text-justify"><p>{{$response->description}} </p></div>
                                            </div>
                                        </div>
                                    @endforeach
                                @endif
                            @endif
                        @endforeach
                    @else
                        <h4 class="fs-6">Sin comentarios...</h4>
                    @endif

                </div>

            </article>

            <article class="margin-l-3-md margin-t-1-5-md">

                <h3 class="mb-4">Últimas Publicaciones</h3>

                <ul class="list-post d-flex flex-column gap-2">
                    @foreach ($posts as $item)
                       <li class="w-15-lg">
                           <a class="text-decoration-none" href="{{route('webSite.blog', $item->slug)}}">{{$item->name}}</a>
                      </li> 
                    @endforeach
                </ul>

            </article>

        </article>


    </section>





</div>



@endsection

resources/views/webSite/contact.blade.php
@extends('layouts.app')

@section('content')

<div class="main-container">

    <section class="position-relative">
        <div class="hero__layer"></div>
         <div class="hero__section text-light d-none  d-md-flex align-items-center gap-2 position-absolute"><i class="icon-home fs-3"></i><i class="icon-circle font-s-0-2"></i> <span class="font-w-7 l-spacing-5 fs-3">Contáctenos</span></div>

     <picture >
         <source srcset="../../assets/img/consultancy_d.webp" media="(min-width:768px)">
          <img class="hero_home-image w-100" src="../../assets/img/consultancy_m.webp" alt="Comunicate con Cv Auditores de Colombia SAS">
       </picture>
    </section>

    <section class="d-flex flex-column flex-lg-row justify-content-lg-around">
        <article>

            <div class="h-5 pt-3 w-75 mx-auto ">

                @include('layouts.alert')

            </div>

            <div class="container-form m-auto color-dark">
                <div class="mt-5 mb-4">
                    <h3 class="fw-bold ">Contáctenos llenando el siguiente formulario</h3>
                </div>
                <form id="contact-form" class="" method="POST" action="{{route('service.contact')}}" class="color-dark">
                    @csrf
                    <div class="d-flex flex-column py-3">
                        <label class="mb-2 fw-bold" for="">Nombres y apellidos</label>
                        <input id="input-name-contact" class="p-2 form__input" name="name" value="{{ old('name') }}" type="text" required>
                        @error('name')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="d-flex flex-column  py-3">
                        <label class="mb-2 fw-bold" for="">Empresa</label>
                        <input  id="input-company-contact"  class="p-2 form__input" name="company" value="{{ old('company') }}" type="text" required>
                        @error('company')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="d-flex flex-column  py-3">
                        <label class="mb-2 fw-bold" for="">Correo electrónico</label>
                        <input  id="input-email-contact"  class="p-2 form__input" name="email" value="{{ old('email') }}" type="email" required>
                        @error('email')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="d-flex flex-column  py-3">
                        <label class="mb-2 fw-bold" for="">Teléfono</label>
                        <input  id="input-phone-contact"  class="p-2 form__input" name="phone" value="{{ old('phone') }}" type="number" required>
                        @error('phone')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="d-flex flex-column  py-3">
                        <label class="mb-2 fw-bold" for="">Ciudad</label>
                        <input  id="input-city-contact" class="p-2 form__input"  name="city" value="{{ old('city') }}" type="text">
                        @error('city')
                            <span class="text-danger" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                    </div>
                    <div class="d-flex flex-column py-3">
                        <label class="mb-2 fw-bold" for="">Servicios</label>
                        <select class="p-2 form__input" name="service" value="{{ old('service') }}" aria-placeholder="Servicios" required>
                            @foreach ($servicesGlobal as $item)
                                <option value="{{$item->id}}">{{$item->name}}</option>
                            @endforeach
                        </select>
                    </div>
                    <div class="d-flex flex-column py-3">
                        <label class="mb-2 fw-bold" for="">Mensaje</label>
                        <textarea id="input-message-contact"  class="form__input resize-none" name="message" value="{{ old('message') }}" cols="30" rows="10"></textarea>
                    </div>
                    <div>
                        <input id="input-check-contact"  type="checkbox" name="term" value="{{ old('term') }}" required>
                        <p>Acepto y he leído la Autorización para el tratamiento <a href="../../public/docs/portafolio_de_servicios_cv_auditores.pdf" download="">de datos personales y política de tratamiento de datos</a> </p>
                    </div>
                    
                    <button class="btn btn-danger" type="submit">Enviar</button>

                    <div class="msm-error h-5 d-flex align-items-center">
                        <span class="text-primary"></span>
                    </div>
                </form>
            </div>

        </article>

        <article class="my-4 lg-p-top-4">
            <div class=" cards card--md  d-flex flex-column back-white p-3 my-2">
                  <div class="text-primary py-1">
                    <span class="" >+57 317 639 4275</span>
                  </div>
                  <div class="text-primary py-1 ">
                    <span class="" >gerencia@cvauditoresbq.com</span>
                  </div>
                  <div class=" py-1">
                    <span class="" >Calle 82 No 49C-50 piso 2</span>
                  </div>
            </div>
            <div class=" cards  card--md d-flex flex-column back-white p-3 mt-5" >
                <span class="text-primary ms-1">Siguenos:</span>

                <div class="d-flex flex-column">
                    <a class="text-decoration-none py-1" href=""><i class="icon-facebook-squared "></i><span class="">Facebook</span></a>
                    <a class="text-decoration-none py-1" href=""><i class="icon-instagram "></i><span class="">Istagram</span></a>
                    <a class="text-decoration-none py-1" href=""><i class="icon-twitter "></i><span class="">Twitter</span></a>

                </div>
            </div>

        </article>


    </section>


</div>


@endsection

resources/views/webSite/deleteUser.blade.php
@extends('layouts.base')

@section('content')

<div class="container">

    <div class="card text-center">
        <h3>El usuario ha sido eliminado de nuestra base de datos</h3>
    </div>
    <div class="text-center">
        <a class="btn btn-danger" href="{{route('home')}}">Volver al sitio web</a>
    </div>

</div>
    
@endsection

resources/views/webSite/home.blade.php
@extends('layouts.app')

@section('content')

<section>
  <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
      <div class="carousel-item active">
         <picture class="" >
            <source srcset="../../assets/img/hero_porfolio_d.webp" media="(min-width:768px)"> 
             <img class="w-100" src="../../assets/img/hero_porfolio_m.webp" alt="UN EQUIPO DE PROFESIONALES A SU SERVICIO DE CV AUDITORES">

             <div class="carousel-caption d-none d-md-block">
              <span class="fs-3 fw-bold">UN EQUIPO DE PROFESIONALES A SU SERVICIO</span>
            
            </div>
          </picture>
      </div>
      <div class="carousel-item">
         <picture class="" >
            <source srcset="../../assets/img/hero_service_d.webp" media="(min-width:768px)"> 
             <img class="w-100" src="../../assets/img/hero_service_m.webp" alt="CV AUDITORES OFRECE SERVICIO ESPECIALIZADO PARA SUS PROCESOS">

             <div class="carousel-caption d-none d-md-block">
              <span class="fs-3 fw-bold">SERVICIO ESPECIALIZADO PARA SUS PROCESOS</span>
            
            </div>
          </picture>
      </div>
      <div class="carousel-item">
         <picture class="" >
            <source srcset="../../assets/img/hero_teem_d.webp" media="(min-width:768px)"> 
             <img class="w-100" src="../../assets/img/hero_teem_m.webp" alt="UN PORTAFOLIO DE SERVICIOS">

             <div class="carousel-caption d-none d-md-block">
              <span class="fs-3 fw-bold">UN PORTAFOLIO DE SERVICIOS AJUSTADO A SU NECESIDAD</span>
            
            </div>
          </picture>
      </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</section>
    
<section>
    <article class="card__article d-md-flex justify-content-center">
      <div class="">
          <div class="card__title mb-4">
              <h2 class="title title-sm">¿Quiénes Somos?</h2>
        </div>

        <div class="card__about"><p><strong>CV AUDITORES DE COLOMBIA SAS.</strong> Es una empresa legalmente constituida desde el 2003 que nació por iniciativa y finalidad para satisfacer las necesidades de nuestros clientes, entidades públicas, privadas o particulares, y se ha dedicado a crecer con un excelente servicio, calidad y cumplimiento en el trabajo </p></div>
        
      </div >
      <div class="">
          <div class="card__title mb-4">
              <h2 class="title title-sm">Nuestro Compromiso</h2>
        </div>

        <div class="card__about"><p><strong>CV AUDITORES DE COLOMBIA SAS.</strong> enmarcada dentro de las normas de ética, se ha orientado hacia dos objetivos: Brindar nuestros servicios profesionales para comprender y solucionar las necesidades de nuestros clientes. Ofrecer servicios cuyos resultados justifiquen su costo </p></div>

      </div>

    </article>

   <article>

          

   </article>

</section>
    
<section class="porfolio w-100 position-relative">
  <div class="porfolio__layer position-absolute w-100 d-flex flex-column justify-content-center">
      <div class="porfolio__container d-flex flex-column justify-content-center gap-2">
          <span class="porfolio__title text-light fw-light f-san-serif mb-3">Conoce más</span>
          <p class="porfolio__text text-light fw-bold f-san-serif">NUESTRO PORTAFOLIO</p>
          <a href="../../docs/portafolio_de_servicios_cv_auditores.pdf" download="" class="border-0 rounded button--md button--gray text-light text-decoration-none d-flex justify-content-center align-items-center">Ver mas</a >
      </div>
  </div>
  <picture class="" >
      <source srcset="../../assets/img/porfolio_d-1.webp" media="(min-width:1200px)"> 
      <source srcset="../../assets/img/porfolio_d.webp" media="(min-width:768px)"> 
       <img class="hero_home-image w-100" src="../../assets/img/porfolio_m.webp" alt="Portafolio de servicios">
      
      </div>
    </picture>

</section>
 
<section>
  <article class="carousel">
    <div class="text-center margin-top-4">
      <h2 class="title fw-bold">Nuestra Experiencia</h2>

    </div>
        <div  class="slick-list" id="slick-list">
          
             <button class="slick-arrow slick-prev" id="button-prev" data-button="button-prev">
                <i class="icon-left-open"></i>
             </button>

               <div class="slick-track d-flex align-items-center" id="track">

                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-1.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-2.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-3.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-4.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-5.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-6.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-7.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-8.webp" alt="Clientes satisfechos">
                  </div>
                  <div class="slick">
                      <img class="w-100" src="../../assets/img/brand/brand-9.jpg" alt="Clientes satisfechos">
                  </div>
                 

               </div>

              

              <button class="slick-arrow slick-next position-absolute" id="button-next" data-button="button-next">
                  <i class="icon-right-open"></i>
              </button>
        </div>
  </article>

</section>


@endsection

resources/views/webSite/nofaind.blade.php
@extends('layouts.base')

@section('content')

<div class="container">

    <div class="card text-center">
        <h3>El usuario no está registrado en nuestras bases de datos</h3>
    </div>
    <div class="text-center">
        <a class="btn btn-danger" href="{{route('webSite.unsubscription')}}">Volver al formulario</a>
    </div>

</div>

    
@endsection